//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
func nextFibo(current: Int, previous: Int) -> Int {
  return current + previous
}

func updateSum(currentSum: Int, value: Int) -> Int {
  return (value % 2 == 0) ? currentSum + value : currentSum
}

func sumEvenFibo(upto: Int) -> Int {
  var previousValue = 1
  var currentValue = 2
  var sum = 0
  repeat {
    sum = updateSum(currentSum: sum, value: currentValue)

    let nextValue = nextFibo(current: currentValue, previous: previousValue)

    previousValue = currentValue
    currentValue = nextValue
  }
  while currentValue <= upto
  
  return sum
}

print(sumEvenFibo(upto: 4000000))
